const defaultWords2 = [
  {
    value: "wizard",
    type: "noun",
    goesWith: [
      "tossed",
      "cooked",
      "saw",
      "went caroling with",
      "waddled over to",
    ],
  },
  {
    value: "shaman",
    type: "noun",
    goesWith: [
      "tossed",
      "cooked",
      "saw",
      "went caroling with",
      "waddled over to",
    ],
  },
  {
    value: "programmer",
    type: "noun",
    goesWith: [
      "tossed",
      "cooked",
      "saw",
      "went caroling with",
      "harmonized with",
    ],
  },
  {
    value: "cheeseburger",
    type: "noun",
    goesWith: ["looked very tasty to"],
  },
  {
    value: "looked very tasty to",
    type: "verb",
    goesWith: [
      "wizard",
      "programmer",
      "friend",
      "knave",
      "cowboy",
      "doctor",
      "clerk",
      "doctor",
      "shaman",
    ],
  },
  {
    value: "tasty",
    type: "adjective",
    goesWith: ["cheeseburger", "apple"],
  },
  {
    value: "cheerful",
    type: "adjective",
    goesWith: [
      "wizard",
      "programmer",
      "friend",
      "knave",
      "cowboy",
      "doctor",
      "clerk",
      "doctor",
      "shaman",
    ],
  },
  {
    value: "salt-of-the-earth",
    type: "adjective",
    goesWith: [
      "wizard",
      "programmer",
      "friend",
      "knave",
      "cowboy",
      "doctor",
      "clerk",
      "doctor",
      "shaman",
    ],
  },
  {
    value: "cooked",
    type: "verb",
    goesWith: ["cheeseburger", "apple"],
  },
  {
    value: "saw",
    type: "verb",
    goesWith: ["cheeseburger", "wizard", "programmer", "friend", "duck", "knave"],
  },
  //
  {
    value: "tossed",
    type: "verb",
    goesWith: ["apple", "ball"],
  },
  {
    value: "met",
    type: "verb",
    goesWith: [
      "wizard",
      "programmer",
      "friend",
      "duck",
      "knave",
      "cowboy",
      "doctor",
    ],
  },
  {
    value: "friend",
    type: "noun",
    goesWith: ["tossed", "cooked", "saw"],
  },
  {
    value: "apple",
    type: "noun",
    goesWith: [],
  },
  {
    value: "clerk",
    type: "noun",
    goesWith: [
      "tossed",
      "cooked",
      "saw",
      "went caroling with",
      "was jealous of",
      "harmonized with",
    ],
  },
  {
    value: "duck",
    type: "noun",
    goesWith: ["saw", "waddled over to"],
  },
  {
    value: "no-nonsense",
    type: "adjective",
    goesWith: [
      "wizard",
      "programmer",
      "friend",
      "duck",
      "knave",
      "cowboy",
      "doctor",
      "clerk",
      "doctor",
      "shaman",
    ],
  },
  {
    value: "nimble",
    type: "adjective",
    goesWith: [
      "wizard",
      "programmer",
      "friend",
      "duck",
      "knave",
      "cowboy",
      "doctor",
      "clerk",
      "doctor",
      "shaman",
    ],
  },
  {
    value: "doctor",
    type: "noun",
    goesWith: [
      "tossed",
      "cooked",
      "saw",
      "went caroling with",
      "was jealous of",
      "harmonized with",
    ],
  },
  {
    value: "cowboy",
    type: "noun",
    goesWith: [
      "tossed",
      "cooked",
      "saw",
      "went caroling with",
      "was jealous of",
      "harmonized with",
    ],
  },
  {
    value: "went caroling with",
    type: "verb",
    goesWith: [
      "wizard",
      "programmer",
      "friend",
      "knave",
      "doctor",
      "clerk",
      "shaman",
      "doctor",
    ],
  },
  {
    value: "was jealous of",
    type: "verb",
    goesWith: [
      "wizard",
      "programmer",
      "friend",
      "knave",
      "doctor",
      "clerk",
      "shaman",
      "doctor",
    ],
  },
  {
    value: "waddled over to",
    type: "verb",
    goesWith: [
      "cheeseburger",
      "wizard",
      "programmer",
      "friend",
      "knave",
      "doctor",
      "clerk",
      "shaman",
      "doctor",
    ],
  },
  {
    value: "iridescent",
    type: "adjective",
    goesWith: [],
  },
  {
    value: "rectangular",
    type: "adjective",
    goesWith: [],
  },
  {
    value: "colossal",
    type: "adjective",
    goesWith: [],
  },
  {
    value: "infinite",
    type: "adjective",
    goesWith: [],
  },
];

module.exports = { defaultWords2 };
